import type { IPlace } from '@/utils/interfaces'

export const mockPlaces: IPlace[] = [
  {
    id: '1',
    name: 'Misty Mountain Retreat',
    placeType: 'hotel',
    address: '12 Pine Ridge',
    city: 'Da Lat',
    country: 'Vietnam',
    location: {
      type: 'Point',
      coordinates: [108.458, 11.94],
    },
    mainImageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.8,
    reviewCount: 124,
    description: 'Cozy cabins tucked away in the pine forests with panoramic valley views.',
    pricePerNight: 120,
    amenities: ['spa', 'breakfast', 'wifi'],
    tags: [
      { id: 'tag-mountain', name: 'Mountain' },
      { id: 'tag-nature', name: 'Nature' },
      { id: 'tag-relax', name: 'Relax' },
    ],
  },
  {
    id: '2',
    name: 'Sunset Coastline Walk',
    placeType: 'landmark',
    address: 'Bai Truoc Promenade',
    city: 'Vung Tau',
    country: 'Vietnam',
    location: {
      type: 'Point',
      coordinates: [107.084, 10.346],
    },
    mainImageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.6,
    reviewCount: 203,
    description: 'Experience golden hour along a dramatic shoreline filled with hidden coves.',
    tags: [
      { id: 'tag-beach', name: 'Beach' },
      { id: 'tag-sunset', name: 'Sunset' },
      { id: 'tag-walk', name: 'Walk' },
    ],
    priceRange: '$$',
  },
  {
    id: '3',
    name: 'Old Quarter Coffee Crawl',
    placeType: 'restaurant',
    address: '36 Hang Gai',
    city: 'Hanoi',
    country: 'Vietnam',
    location: {
      type: 'Point',
      coordinates: [105.848, 21.033],
    },
    mainImageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.7,
    reviewCount: 89,
    description: 'Discover heritage coffee houses and modern brews in the heart of the city.',
    priceRange: '$$',
    cuisineType: 'Cafe',
    openingHours: {
      mon: '7-22',
      tue: '7-22',
      wed: '7-22',
      thu: '7-22',
      fri: '7-23',
      sat: '7-23',
      sun: '7-22',
    },
    tags: [
      { id: 'tag-coffee', name: 'Coffee' },
      { id: 'tag-culture', name: 'Culture' },
      { id: 'tag-city', name: 'City' },
    ],
  },
  {
    id: '4',
    name: 'Riverfront Night Market',
    placeType: 'restaurant',
    address: 'Hoa Binh Street',
    city: 'Da Nang',
    country: 'Vietnam',
    location: {
      type: 'Point',
      coordinates: [108.202, 16.067],
    },
    mainImageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.5,
    reviewCount: 310,
    description: 'Street food, lanterns, and river breezes make this a lively evening stop.',
    priceRange: '$',
    tags: [
      { id: 'tag-streetfood', name: 'Street Food' },
      { id: 'tag-nightlife', name: 'Nightlife' },
      { id: 'tag-market', name: 'Market' },
    ],
  },
  {
    id: '5',
    name: 'Cascading Rice Terraces',
    placeType: 'landmark',
    address: 'Mu Cang Chai',
    city: 'Yen Bai',
    country: 'Vietnam',
    location: {
      type: 'Point',
      coordinates: [104.138, 21.856],
    },
    mainImageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.9,
    reviewCount: 142,
    description: 'Layered terraces that glow golden at harvest season.',
    tags: [
      { id: 'tag-rice', name: 'Rice Terraces' },
      { id: 'tag-nature2', name: 'Nature' },
      { id: 'tag-photo', name: 'Photography' },
    ],
  },
  {
    id: '6',
    name: 'Hidden Rooftop Bar',
    placeType: 'restaurant',
    address: '45 Nguyen Trai',
    city: 'Ho Chi Minh City',
    country: 'Vietnam',
    location: { type: 'Point', coordinates: [106.695, 10.776] },
    mainImageUrl: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.4,
    reviewCount: 78,
    description: 'Craft cocktails and skyline views above the city lights.',
    priceRange: '$$$',
    tags: [
      { id: 'tag-rooftop', name: 'Rooftop' },
      { id: 'tag-cocktails', name: 'Cocktails' },
      { id: 'tag-night', name: 'Nightlife' },
    ],
  },
  {
    id: '7',
    name: 'Lan Ha Bay Kayak',
    placeType: 'landmark',
    address: 'Lan Ha Bay',
    city: 'Hai Phong',
    country: 'Vietnam',
    location: { type: 'Point', coordinates: [107.055, 20.784] },
    mainImageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.9,
    reviewCount: 256,
    description: 'Paddle through limestone karsts and emerald waters.',
    ticketPrice: 35,
    tags: [
      { id: 'tag-kayak', name: 'Kayak' },
      { id: 'tag-sea', name: 'Sea' },
      { id: 'tag-adventure', name: 'Adventure' },
    ],
  },
  {
    id: '8',
    name: 'Hoi An Lantern Stay',
    placeType: 'hotel',
    address: '21 Tran Phu',
    city: 'Hoi An',
    country: 'Vietnam',
    location: { type: 'Point', coordinates: [108.325, 15.879] },
    mainImageUrl: 'https://images.unsplash.com/photo-1501117716987-c8e1ecb210af?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.7,
    reviewCount: 133,
    description: 'Boutique rooms tucked inside the Ancient Town.',
    pricePerNight: 95,
    amenities: ['breakfast', 'bikes', 'wifi'],
    tags: [
      { id: 'tag-heritage', name: 'Heritage' },
      { id: 'tag-lantern', name: 'Lanterns' },
      { id: 'tag-riverside', name: 'Riverside' },
    ],
  },
  {
    id: '9',
    name: 'Sapa Cloud Trail',
    placeType: 'landmark',
    address: 'Fansipan Road',
    city: 'Sa Pa',
    country: 'Vietnam',
    location: { type: 'Point', coordinates: [103.844, 22.336] },
    mainImageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.8,
    reviewCount: 198,
    description: 'Mountain trek with clouds rolling over terraced hills.',
    tags: [
      { id: 'tag-hike', name: 'Hiking' },
      { id: 'tag-mountain2', name: 'Mountains' },
      { id: 'tag-cold', name: 'Cool Weather' },
    ],
  },
  {
    id: '10',
    name: 'Hue Imperial Feast',
    placeType: 'restaurant',
    address: '2 Le Loi',
    city: 'Hue',
    country: 'Vietnam',
    location: { type: 'Point', coordinates: [107.580, 16.463] },
    mainImageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.6,
    reviewCount: 112,
    description: 'Royal recipes with a view of the Perfume River.',
    priceRange: '$$$',
    cuisineType: 'Vietnamese',
    tags: [
      { id: 'tag-royal', name: 'Royal Cuisine' },
      { id: 'tag-river', name: 'Riverside' },
      { id: 'tag-fine', name: 'Fine Dining' },
    ],
  },
  {
    id: '11',
    name: 'Desert Dunes Camp',
    placeType: 'hotel',
    address: 'Erg Chebbi',
    city: 'Merzouga',
    country: 'Morocco',
    location: { type: 'Point', coordinates: [-3.995, 31.110] },
    mainImageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.7,
    reviewCount: 94,
    description: 'Luxury tents under the Sahara stars.',
    pricePerNight: 210,
    amenities: ['dinner', 'camel ride', 'wifi'],
    tags: [
      { id: 'tag-desert', name: 'Desert' },
      { id: 'tag-glamping', name: 'Glamping' },
      { id: 'tag-stargaze', name: 'Stargazing' },
    ],
  },
  {
    id: '12',
    name: 'Northern Lights Lodge',
    placeType: 'hotel',
    address: 'Arctic Circle 12',
    city: 'Tromsø',
    country: 'Norway',
    location: { type: 'Point', coordinates: [18.955, 69.649] },
    mainImageUrl: 'https://images.unsplash.com/photo-1503264116251-35a269479413?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.9,
    reviewCount: 221,
    description: 'Glass-roof cabins for aurora watching.',
    pricePerNight: 320,
    amenities: ['sauna', 'breakfast', 'wifi'],
    tags: [
      { id: 'tag-aurora', name: 'Aurora' },
      { id: 'tag-cabin', name: 'Cabin' },
      { id: 'tag-snow', name: 'Snow' },
    ],
  },
  {
    id: '13',
    name: 'Santorini Cliff Suites',
    placeType: 'hotel',
    address: 'Oia Caldera',
    city: 'Santorini',
    country: 'Greece',
    location: { type: 'Point', coordinates: [25.375, 36.461] },
    mainImageUrl: 'https://images.unsplash.com/photo-1505739775417-85f81d90c356?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.8,
    reviewCount: 305,
    description: 'Infinity pools with sweeping Aegean views.',
    pricePerNight: 450,
    amenities: ['pool', 'breakfast', 'wifi'],
    tags: [
      { id: 'tag-sunset2', name: 'Sunset' },
      { id: 'tag-view', name: 'View' },
      { id: 'tag-lux', name: 'Luxury' },
    ],
  },
  {
    id: '14',
    name: 'Tokyo Night Food Tour',
    placeType: 'restaurant',
    address: 'Shinjuku',
    city: 'Tokyo',
    country: 'Japan',
    location: { type: 'Point', coordinates: [139.700, 35.689] },
    mainImageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.7,
    reviewCount: 188,
    description: 'Street eats, izakayas, and neon-lit alleys.',
    priceRange: '$$',
    cuisineType: 'Japanese',
    tags: [
      { id: 'tag-street', name: 'Street Food' },
      { id: 'tag-night2', name: 'Night' },
      { id: 'tag-tour', name: 'Guided Tour' },
    ],
  },
  {
    id: '15',
    name: 'Patagonia Glacier Hike',
    placeType: 'landmark',
    address: 'Perito Moreno',
    city: 'El Calafate',
    country: 'Argentina',
    location: { type: 'Point', coordinates: [-72.998, -50.483] },
    mainImageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.9,
    reviewCount: 167,
    description: 'Ice trekking with thundering glacier views.',
    ticketPrice: 65,
    tags: [
      { id: 'tag-glacier', name: 'Glacier' },
      { id: 'tag-hike2', name: 'Hike' },
      { id: 'tag-ice', name: 'Ice' },
    ],
  },
  {
    id: '16',
    name: 'Cappadocia Balloon Dawn',
    placeType: 'landmark',
    address: 'Goreme Valley',
    city: 'Cappadocia',
    country: 'Turkey',
    location: { type: 'Point', coordinates: [34.852, 38.643] },
    mainImageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.8,
    reviewCount: 284,
    description: 'Sunrise balloons over fairy chimneys.',
    ticketPrice: 180,
    tags: [
      { id: 'tag-balloon', name: 'Balloon' },
      { id: 'tag-sunrise', name: 'Sunrise' },
      { id: 'tag-photo2', name: 'Photography' },
    ],
  },
  {
    id: '17',
    name: 'Lisbon Tile Walk',
    placeType: 'landmark',
    address: 'Alfama',
    city: 'Lisbon',
    country: 'Portugal',
    location: { type: 'Point', coordinates: [-9.130, 38.713] },
    mainImageUrl: 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=900&q=80',
    averageRating: 4.5,
    reviewCount: 119,
    description: 'Tram rides, azulejo alleys, and miradouros.',
    tags: [
      { id: 'tag-tram', name: 'Tram' },
      { id: 'tag-tiles', name: 'Azulejos' },
      { id: 'tag-view2', name: 'Viewpoint' },
    ],
  },
]


