import type { IPlace, IForumPost } from "@/utils/interfaces";

export const mockPlaces: IPlace[] = [
  {
    id: "1",
    name: "Misty Mountain Retreat",
    placeType: "hotel",
    address: "12 Pine Ridge",
    city: "Da Lat",
    country: "Vietnam",
    location: {
      type: "Point",
      coordinates: [108.458, 11.94],
    },
    mainImageUrl:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.8,
    reviewCount: 124,
    description:
      "Cozy cabins tucked away in the pine forests with panoramic valley views.",
    pricePerNight: 120,
    amenities: ["spa", "breakfast", "wifi"],
    tags: [
      { id: "tag-mountain", name: "Mountain" },
      { id: "tag-nature", name: "Nature" },
      { id: "tag-relax", name: "Relax" },
    ],
  },
  {
    id: "2",
    name: "Sunset Coastline Walk",
    placeType: "landmark",
    address: "Bai Truoc Promenade",
    city: "Vung Tau",
    country: "Vietnam",
    location: {
      type: "Point",
      coordinates: [107.084, 10.346],
    },
    mainImageUrl:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.6,
    reviewCount: 203,
    description:
      "Experience golden hour along a dramatic shoreline filled with hidden coves.",
    tags: [
      { id: "tag-beach", name: "Beach" },
      { id: "tag-sunset", name: "Sunset" },
      { id: "tag-walk", name: "Walk" },
    ],
    priceRange: "$$",
  },
  {
    id: "3",
    name: "Old Quarter Coffee Crawl",
    placeType: "restaurant",
    address: "36 Hang Gai",
    city: "Hanoi",
    country: "Vietnam",
    location: {
      type: "Point",
      coordinates: [105.848, 21.033],
    },
    mainImageUrl:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.7,
    reviewCount: 89,
    description:
      "Discover heritage coffee houses and modern brews in the heart of the city.",
    priceRange: "$$",
    cuisineType: "Cafe",
    openingHours: {
      mon: "7-22",
      tue: "7-22",
      wed: "7-22",
      thu: "7-22",
      fri: "7-23",
      sat: "7-23",
      sun: "7-22",
    },
    tags: [
      { id: "tag-coffee", name: "Coffee" },
      { id: "tag-culture", name: "Culture" },
      { id: "tag-city", name: "City" },
    ],
  },
  {
    id: "4",
    name: "Riverfront Night Market",
    placeType: "restaurant",
    address: "Hoa Binh Street",
    city: "Da Nang",
    country: "Vietnam",
    location: {
      type: "Point",
      coordinates: [108.202, 16.067],
    },
    mainImageUrl:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.5,
    reviewCount: 310,
    description:
      "Street food, lanterns, and river breezes make this a lively evening stop.",
    priceRange: "$",
    tags: [
      { id: "tag-streetfood", name: "Street Food" },
      { id: "tag-nightlife", name: "Nightlife" },
      { id: "tag-market", name: "Market" },
    ],
  },
  {
    id: "5",
    name: "Cascading Rice Terraces",
    placeType: "landmark",
    address: "Mu Cang Chai",
    city: "Yen Bai",
    country: "Vietnam",
    location: {
      type: "Point",
      coordinates: [104.138, 21.856],
    },
    mainImageUrl:
      "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.9,
    reviewCount: 142,
    description: "Layered terraces that glow golden at harvest season.",
    tags: [
      { id: "tag-rice", name: "Rice Terraces" },
      { id: "tag-nature2", name: "Nature" },
      { id: "tag-photo", name: "Photography" },
    ],
  },
  {
    id: "6",
    name: "Hidden Rooftop Bar",
    placeType: "restaurant",
    address: "45 Nguyen Trai",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    location: { type: "Point", coordinates: [106.695, 10.776] },
    mainImageUrl:
      "https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.4,
    reviewCount: 78,
    description: "Craft cocktails and skyline views above the city lights.",
    priceRange: "$$$",
    tags: [
      { id: "tag-rooftop", name: "Rooftop" },
      { id: "tag-cocktails", name: "Cocktails" },
      { id: "tag-night", name: "Nightlife" },
    ],
  },
  {
    id: "7",
    name: "Lan Ha Bay Kayak",
    placeType: "landmark",
    address: "Lan Ha Bay",
    city: "Hai Phong",
    country: "Vietnam",
    location: { type: "Point", coordinates: [107.055, 20.784] },
    mainImageUrl:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.9,
    reviewCount: 256,
    description: "Paddle through limestone karsts and emerald waters.",
    ticketPrice: 35,
    tags: [
      { id: "tag-kayak", name: "Kayak" },
      { id: "tag-sea", name: "Sea" },
      { id: "tag-adventure", name: "Adventure" },
    ],
  },
  {
    id: "8",
    name: "Hoi An Lantern Stay",
    placeType: "hotel",
    address: "21 Tran Phu",
    city: "Hoi An",
    country: "Vietnam",
    location: { type: "Point", coordinates: [108.325, 15.879] },
    mainImageUrl:
      "https://images.unsplash.com/photo-1501117716987-c8e1ecb210af?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.7,
    reviewCount: 133,
    description: "Boutique rooms tucked inside the Ancient Town.",
    pricePerNight: 95,
    amenities: ["breakfast", "bikes", "wifi"],
    tags: [
      { id: "tag-heritage", name: "Heritage" },
      { id: "tag-lantern", name: "Lanterns" },
      { id: "tag-riverside", name: "Riverside" },
    ],
  },
  {
    id: "9",
    name: "Sapa Cloud Trail",
    placeType: "landmark",
    address: "Fansipan Road",
    city: "Sa Pa",
    country: "Vietnam",
    location: { type: "Point", coordinates: [103.844, 22.336] },
    mainImageUrl:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.8,
    reviewCount: 198,
    description: "Mountain trek with clouds rolling over terraced hills.",
    tags: [
      { id: "tag-hike", name: "Hiking" },
      { id: "tag-mountain2", name: "Mountains" },
      { id: "tag-cold", name: "Cool Weather" },
    ],
  },
  {
    id: "10",
    name: "Hue Imperial Feast",
    placeType: "restaurant",
    address: "2 Le Loi",
    city: "Hue",
    country: "Vietnam",
    location: { type: "Point", coordinates: [107.58, 16.463] },
    mainImageUrl:
      "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.6,
    reviewCount: 112,
    description: "Royal recipes with a view of the Perfume River.",
    priceRange: "$$$",
    cuisineType: "Vietnamese",
    tags: [
      { id: "tag-royal", name: "Royal Cuisine" },
      { id: "tag-river", name: "Riverside" },
      { id: "tag-fine", name: "Fine Dining" },
    ],
  },
  {
    id: "11",
    name: "Desert Dunes Camp",
    placeType: "hotel",
    address: "Erg Chebbi",
    city: "Merzouga",
    country: "Morocco",
    location: { type: "Point", coordinates: [-3.995, 31.11] },
    mainImageUrl:
      "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.7,
    reviewCount: 94,
    description: "Luxury tents under the Sahara stars.",
    pricePerNight: 210,
    amenities: ["dinner", "camel ride", "wifi"],
    tags: [
      { id: "tag-desert", name: "Desert" },
      { id: "tag-glamping", name: "Glamping" },
      { id: "tag-stargaze", name: "Stargazing" },
    ],
  },
  {
    id: "12",
    name: "Northern Lights Lodge",
    placeType: "hotel",
    address: "Arctic Circle 12",
    city: "Tromsø",
    country: "Norway",
    location: { type: "Point", coordinates: [18.955, 69.649] },
    mainImageUrl:
      "https://images.unsplash.com/photo-1503264116251-35a269479413?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.9,
    reviewCount: 221,
    description: "Glass-roof cabins for aurora watching.",
    pricePerNight: 320,
    amenities: ["sauna", "breakfast", "wifi"],
    tags: [
      { id: "tag-aurora", name: "Aurora" },
      { id: "tag-cabin", name: "Cabin" },
      { id: "tag-snow", name: "Snow" },
    ],
  },
  {
    id: "13",
    name: "Santorini Cliff Suites",
    placeType: "hotel",
    address: "Oia Caldera",
    city: "Santorini",
    country: "Greece",
    location: { type: "Point", coordinates: [25.375, 36.461] },
    mainImageUrl:
      "https://images.unsplash.com/photo-1505739775417-85f81d90c356?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.8,
    reviewCount: 305,
    description: "Infinity pools with sweeping Aegean views.",
    pricePerNight: 450,
    amenities: ["pool", "breakfast", "wifi"],
    tags: [
      { id: "tag-sunset2", name: "Sunset" },
      { id: "tag-view", name: "View" },
      { id: "tag-lux", name: "Luxury" },
    ],
  },
  {
    id: "14",
    name: "Tokyo Night Food Tour",
    placeType: "restaurant",
    address: "Shinjuku",
    city: "Tokyo",
    country: "Japan",
    location: { type: "Point", coordinates: [139.7, 35.689] },
    mainImageUrl:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.7,
    reviewCount: 188,
    description: "Street eats, izakayas, and neon-lit alleys.",
    priceRange: "$$",
    cuisineType: "Japanese",
    tags: [
      { id: "tag-street", name: "Street Food" },
      { id: "tag-night2", name: "Night" },
      { id: "tag-tour", name: "Guided Tour" },
    ],
  },
  {
    id: "15",
    name: "Patagonia Glacier Hike",
    placeType: "landmark",
    address: "Perito Moreno",
    city: "El Calafate",
    country: "Argentina",
    location: { type: "Point", coordinates: [-72.998, -50.483] },
    mainImageUrl:
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.9,
    reviewCount: 167,
    description: "Ice trekking with thundering glacier views.",
    ticketPrice: 65,
    tags: [
      { id: "tag-glacier", name: "Glacier" },
      { id: "tag-hike2", name: "Hike" },
      { id: "tag-ice", name: "Ice" },
    ],
  },
  {
    id: "16",
    name: "Cappadocia Balloon Dawn",
    placeType: "landmark",
    address: "Goreme Valley",
    city: "Cappadocia",
    country: "Turkey",
    location: { type: "Point", coordinates: [34.852, 38.643] },
    mainImageUrl:
      "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.8,
    reviewCount: 284,
    description: "Sunrise balloons over fairy chimneys.",
    ticketPrice: 180,
    tags: [
      { id: "tag-balloon", name: "Balloon" },
      { id: "tag-sunrise", name: "Sunrise" },
      { id: "tag-photo2", name: "Photography" },
    ],
  },
  {
    id: "17",
    name: "Lisbon Tile Walk",
    placeType: "landmark",
    address: "Alfama",
    city: "Lisbon",
    country: "Portugal",
    location: { type: "Point", coordinates: [-9.13, 38.713] },
    mainImageUrl:
      "https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=900&q=80",
    averageRating: 4.5,
    reviewCount: 119,
    description: "Tram rides, azulejo alleys, and miradouros.",
    tags: [
      { id: "tag-tram", name: "Tram" },
      { id: "tag-tiles", name: "Azulejos" },
      { id: "tag-view2", name: "Viewpoint" },
    ],
  },
];

export const mockForumPosts: IForumPost[] = [
  {
    id: "1",
    title: "Hidden gems in Kyoto/Osaka?",
    contentSnippet:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.",
    content:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    author: {
      id: "user1",
      username: "Elon Musk",
    },
    tags: [
      { id: "tag-japan", name: "Japan" },
      { id: "tag-food", name: "Food" },
    ],
    replyCount: 13100,
    createdAt: "2025-05-29T10:00:00Z",
    images: [
      "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1528360983277-13d9b152c6d1?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?auto=format&fit=crop&w=900&q=80",
    ],
    replies: [],
  },
  {
    id: "2",
    title: "Best time to visit Iceland?",
    contentSnippet:
      "Planning a trip to see the Northern Lights. Is November too cold? Any advice on driving conditions?",
    content:
      "I really want to see the Aurora Borealis. I heard November is good but I am worried about the roads.",
    author: {
      id: "user2",
      username: "Traveler Joe",
    },
    tags: [
      { id: "tag-iceland", name: "Iceland" },
      { id: "tag-nature", name: "Nature" },
      { id: "tag-aurora", name: "Aurora" },
    ],
    replyCount: 45,
    createdAt: "2025-06-01T15:30:00Z",
    images: [
      "https://images.unsplash.com/photo-1476900543704-4312b78632f8?auto=format&fit=crop&w=900&q=80",
    ],
    replies: [],
  },
  {
    id: "3",
    title: "Backpacking unrelated question",
    contentSnippet:
      "Just checking if this forum supports text only posts. Lorem ipsum dolor sit amet.",
    content: "Full content of the text only post.",
    author: {
      id: "user3",
      username: "Alice",
    },
    tags: [{ id: "tag-budget", name: "Budget" }],
    replyCount: 2,
    createdAt: "2025-06-02T09:00:00Z",
    replies: [],
  },
  {
    id: "4",
    title: "Street food in Vietnam",
    contentSnippet:
      "Where can I find the best Bun Cha in Hanoi? I have tried a few places but looking for local recommendations.",
    author: {
      id: "user1",
      username: "Elon Musk",
    },
    tags: [
      { id: "tag-vietnam", name: "Vietnam" },
      { id: "tag-food", name: "Street Food" },
    ],
    replyCount: 850,
    createdAt: "2025-05-30T12:00:00Z",
    images: [
      "https://images.unsplash.com/photo-1583417319070-4a69db38a482?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?auto=format&fit=crop&w=900&q=80",
    ],
    replies: [],
  },
  {
    id: "5",
    title: "Solo travel in Paris - Safety tips?",
    contentSnippet:
      "I am planning my first solo trip to Paris next month. Any areas I should avoid at night?",
    content: "Longer content about safety concerns...",
    author: { id: "u5", username: "Sarah J" },
    tags: [
      { id: "t-paris", name: "Paris" },
      { id: "t-safety", name: "Safety" },
    ],
    replyCount: 120,
    createdAt: "2025-05-25T14:00:00Z",
  },
  {
    id: "6",
    title: "Best sushi in Tokyo on a budget",
    contentSnippet:
      "Not looking for Jiro dreams of sushi prices, just good quality affordable spots.",
    content: "Details about budget...",
    author: { id: "u6", username: "Mike R" },
    tags: [
      { id: "t-tokyo", name: "Japan" },
      { id: "t-food", name: "Food" },
      { id: "t-budget", name: "Budget" },
    ],
    replyCount: 89,
    createdAt: "2025-05-20T11:30:00Z",
  },
  {
    id: "7",
    title: "Road trip across USA - Route 66",
    contentSnippet:
      "Is it still worth doing the full Route 66? or are there better alternatives?",
    content: "Full itinerary idea...",
    author: { id: "u7", username: "Roadie" },
    tags: [
      { id: "t-usa", name: "USA" },
      { id: "t-roadtrip", name: "Road Trip" },
    ],
    replyCount: 230,
    createdAt: "2025-05-15T09:15:00Z",
  },
  {
    id: "8",
    title: "Packing for winter in Norway",
    contentSnippet: "How many layers do I really need for Tromso in January?",
    content: "Details on clothing...",
    author: { id: "u8", username: "ColdFeet" },
    tags: [
      { id: "t-norway", name: "Norway" },
      { id: "t-packing", name: "Packing" },
    ],
    replyCount: 56,
    createdAt: "2025-05-18T16:45:00Z",
  },
  {
    id: "9",
    title: "Digital Nomad Visa in Spain",
    contentSnippet:
      "Has anyone successfully applied recently? How long did it take?",
    content: "Application details...",
    author: { id: "u9", username: "NomadLife" },
    tags: [
      { id: "t-spain", name: "Spain" },
      { id: "t-visa", name: "Visa" },
    ],
    replyCount: 312,
    createdAt: "2025-06-03T08:20:00Z",
  },
  {
    id: "10",
    title: "Hiking the Inca Trail",
    contentSnippet:
      "Do I need to book 6 months in advance? Any recommended operators?",
    content: "Hiking plan...",
    author: { id: "u10", username: "HikerX" },
    tags: [
      { id: "t-peru", name: "Peru" },
      { id: "t-hiking", name: "Nature" },
    ],
    replyCount: 150,
    createdAt: "2025-05-10T10:00:00Z",
  },
  {
    id: "11",
    title: "Best beaches in Thailand without crowds",
    contentSnippet: "Looking for hidden gems, not Phuket or Phi Phi.",
    content: "Beach preferences...",
    author: { id: "u11", username: "SunSeeker" },
    tags: [
      { id: "t-thai", name: "Thailand" },
      { id: "t-beach", name: "Nature" },
    ],
    replyCount: 78,
    createdAt: "2025-05-28T13:00:00Z",
  },
  {
    id: "12",
    title: "Vegetarian food in Seoul",
    contentSnippet:
      "Is it hard to find vegetarian options? Any restaurant lists?",
    content: "Dietary restrictions...",
    author: { id: "u12", username: "VeggieTrav" },
    tags: [
      { id: "t-seoul", name: "Korea" },
      { id: "t-food", name: "Food" },
    ],
    replyCount: 42,
    createdAt: "2025-06-01T19:00:00Z",
  },
  {
    id: "13",
    title: "Train travel in Europe - Eurail pass worth it?",
    contentSnippet:
      "Calculating costs for a 2 month trip. Is the pass cheaper?",
    content: "Cost breakdown...",
    author: { id: "u13", username: "TrainFan" },
    tags: [
      { id: "t-eu", name: "Europe" },
      { id: "t-transport", name: "Transport" },
      { id: "t-budget", name: "Budget" },
    ],
    replyCount: 560,
    createdAt: "2025-05-05T15:00:00Z",
  },
  {
    id: "14",
    title: "Scariest travel experience?",
    contentSnippet:
      "Share your horror stories! Mine was missing a flight in Delhi.",
    content: "Story time...",
    author: { id: "u14", username: "StoryTeller" },
    tags: [{ id: "t-story", name: "Discussion" }],
    replyCount: 1205,
    createdAt: "2025-04-20T20:00:00Z",
  },
  {
    id: "15",
    title: "Photography spots in Santorini",
    contentSnippet: "Beside the blue domes, where are the best sunset spots?",
    content: "Camera gear...",
    author: { id: "u15", username: "ShutterBug" },
    tags: [
      { id: "t-greece", name: "Greece" },
      { id: "t-photo", name: "Photography" },
    ],
    replyCount: 95,
    createdAt: "2025-05-22T06:00:00Z",
  },
  {
    id: "16",
    title: "Getting around in Bali",
    contentSnippet: "Scooter vs Driver? I am not confident on a bike.",
    content: "Transport options...",
    author: { id: "u16", username: "BaliBound" },
    tags: [
      { id: "t-bali", name: "Indonesia" },
      { id: "t-transport", name: "Transport" },
    ],
    replyCount: 210,
    createdAt: "2025-05-12T12:00:00Z",
  },
  {
    id: "17",
    title: "Family friendly resorts in Mexico",
    contentSnippet: " traveling with a 2yo and 5yo. Need kids club!",
    content: "Family needs...",
    author: { id: "u17", username: "ParentLife" },
    tags: [
      { id: "t-mexico", name: "Mexico" },
      { id: "t-family", name: "Family" },
    ],
    replyCount: 67,
    createdAt: "2025-05-30T09:30:00Z",
  },
  {
    id: "18",
    title: "Coffee culture in Melbourne",
    contentSnippet: "Best flat white in CBD?",
    content: "Coffee talk...",
    author: { id: "u18", username: "CaffeineAddict" },
    tags: [
      { id: "t-melb", name: "Australia" },
      { id: "t-food", name: "Food" },
    ],
    replyCount: 145,
    createdAt: "2025-06-02T08:00:00Z",
  },
  {
    id: "19",
    title: "Safari on a budget",
    contentSnippet:
      "Is it possible to do a safari in Kenya/Tanzania without spending $5k?",
    content: "Budget planning...",
    author: { id: "u19", username: "WildOne" },
    tags: [
      { id: "t-africa", name: "Africa" },
      { id: "t-budget", name: "Budget" },
      { id: "t-nature", name: "Nature" },
    ],
    replyCount: 180,
    createdAt: "2025-05-14T17:00:00Z",
  },
  {
    id: "20",
    title: "Learning Spanish in Colombia",
    contentSnippet: "Medellin or Bogota for language schools?",
    content: "School options...",
    author: { id: "u20", username: "Student" },
    tags: [
      { id: "t-col", name: "Colombia" },
      { id: "t-learn", name: "Education" },
    ],
    replyCount: 33,
    createdAt: "2025-05-29T11:00:00Z",
  },
  {
    id: "21",
    title: "Van life in New Zealand",
    contentSnippet: "Buying v renting for 3 months?",
    content: "Van life logic...",
    author: { id: "u21", username: "VanLifer" },
    tags: [
      { id: "t-nz", name: "New Zealand" },
      { id: "t-nature", name: "Nature" },
      { id: "t-budget", name: "Budget" },
    ],
    replyCount: 250,
    createdAt: "2025-04-25T13:00:00Z",
  },
  {
    id: "22",
    title: "Visa free countries for Indian passport",
    contentSnippet: "Updated list for 2025?",
    content: "Visa info...",
    author: { id: "u22", username: "DesiTraveler" },
    tags: [{ id: "t-visa", name: "Visa" }],
    replyCount: 900,
    createdAt: "2025-06-03T05:00:00Z",
  },
  {
    id: "23",
    title: "Best street food in Penang",
    contentSnippet: "Laksa and Char Kway Teow recommendations please.",
    content: "Food tour...",
    author: { id: "u23", username: "Foodie" },
    tags: [
      { id: "t-malaysia", name: "Malaysia" },
      { id: "t-food", name: "Food" },
    ],
    replyCount: 112,
    createdAt: "2025-05-26T18:00:00Z",
  },
  {
    id: "24",
    title: "Visiting Chernobyl",
    contentSnippet: "Is it open for tours again?",
    content: "Dark tourism...",
    author: { id: "u24", username: "Curious" },
    tags: [{ id: "t-ukraine", name: "Europe" }],
    replyCount: 410,
    createdAt: "2025-01-10T10:00:00Z",
  },
];
