"""add_post_and_reply_likes_tables

Revision ID: 13161609b814
Revises: 66e79fc17114
Create Date: 2025-12-27 14:24:54.249445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13161609b814'
down_revision: Union[str, Sequence[str], None] = '66e79fc17114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], name=op.f('fk_post_likes_post_id_forum_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_post_likes_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_likes'))
    )
    op.create_table('reply_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reply_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reply_id'], ['post_replies.id'], name=op.f('fk_reply_likes_reply_id_post_replies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_reply_likes_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reply_likes'))
    )
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    op.drop_table('reply_likes')
    op.drop_table('post_likes')
    # ### end Alembic commands ###
