"""empty message

Revision ID: 6d5515e9776c
Revises: 91f7c3e07305
Create Date: 2025-12-27 10:01:27.107250

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d5515e9776c"
down_revision: Union[str, Sequence[str], None] = "91f7c3e07305"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column(
        "content_reports", sa.Column("moderation_target_id", sa.UUID(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_content_reports_moderation_target_id_moderation_targets"),
        "content_reports",
        "moderation_targets",
        ["moderation_target_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("content_reports", "target_type")
    op.drop_column("content_reports", "target_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "content_reports",
        sa.Column("target_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "content_reports",
        sa.Column(
            "target_type", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_content_reports_moderation_target_id_moderation_targets"),
        "content_reports",
        type_="foreignkey",
    )
    op.drop_column("content_reports", "moderation_target_id")
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    # ### end Alembic commands ###
