"""empty message

Revision ID: 91f7c3e07305
Revises: 296eec12c278
Create Date: 2025-12-21 17:33:45.604931

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "91f7c3e07305"
down_revision: Union[str, Sequence[str], None] = "296eec12c278"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "moderation_targets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_moderation_targets")),
    )
    op.create_table(
        "business_verification_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("business_image_url", sa.String(length=255), nullable=False),
        sa.Column("business_description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_business_verification_requests_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_verification_requests")),
    )
    op.create_table(
        "post_replies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["post_replies.id"],
            name=op.f("fk_post_replies_parent_id_post_replies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["forum_posts.id"],
            name=op.f("fk_post_replies_post_id_forum_posts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["profiles.id"], name=op.f("fk_post_replies_user_id_profiles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post_replies")),
    )
    op.drop_table("post_comments")
    # op.drop_table('spatial_ref_sys')
    op.add_column(
        "content_reports",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_column("content_reports", "status")
    op.add_column(
        "profiles",
        sa.Column("ban_until", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.drop_constraint(op.f("uq_profiles_username"), "profiles", type_="unique")
    op.add_column("trips", sa.Column("public", sa.Boolean(), nullable=False))
    op.add_column(
        "trips",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "created_at")
    op.drop_column("trips", "public")
    op.create_unique_constraint(
        op.f("uq_profiles_username"),
        "profiles",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("profiles", "ban_until")
    op.add_column(
        "content_reports",
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    )
    op.drop_column("content_reports", "created_at")
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    op.create_table(
        "post_comments",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("post_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("parent_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["post_comments.id"],
            name=op.f("fk_post_comments_parent_id_post_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["forum_posts.id"],
            name=op.f("fk_post_comments_post_id_forum_posts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["profiles.id"], name=op.f("fk_post_comments_user_id_profiles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post_comments")),
    )
    op.drop_table("post_replies")
    op.drop_table("business_verification_requests")
    op.drop_table("moderation_targets")
    # ### end Alembic commands ###
