"""Update place models with cafe and fix inheritance

Revision ID: b359e922889a
Revises: 166f4b799a2b
Create Date: 2025-12-11 08:58:35.088516

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b359e922889a"
down_revision: Union[str, Sequence[str], None] = "166f4b799a2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cafes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("coffee_specialties", sa.String(length=255), nullable=True),
        sa.Column("amenities", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("price_range", sa.String(length=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"], ["places.id"], name=op.f("fk_cafes_id_places"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cafes")),
    )
    # Removed: op.drop_table('spatial_ref_sys') - PostGIS system table, do not drop
    op.add_column("hotels", sa.Column("hotel_class", sa.Integer(), nullable=True))
    op.drop_column("hotels", "star_rating")
    op.drop_column("landmarks", "description")
    op.add_column("places", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "places",
        sa.Column(
            "opening_hours", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("restaurants", "opening_hours")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "restaurants",
        sa.Column(
            "opening_hours",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("places", "opening_hours")
    op.drop_column("places", "description")
    op.add_column(
        "landmarks",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "hotels",
        sa.Column(
            "star_rating",
            sa.NUMERIC(precision=2, scale=1),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("hotels", "hotel_class")
    # Removed: spatial_ref_sys recreation - PostGIS system table
    op.drop_table("cafes")
    # ### end Alembic commands ###
